// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tecmave.Api.Data;

#nullable disable

namespace Tecmave.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110093456_Fix_Resenas_Fecha_Manual")]
    partial class Fix_Resenas_Fecha_Manual
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Tecmave.Api.Models.AgendamientoModel", b =>
                {
                    b.Property<int>("id_agendamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_agendamiento"));

                    b.Property<int>("cliente_id")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<DateOnly>("fecha_agregada")
                        .HasMaxLength(150)
                        .HasColumnType("date");

                    b.Property<DateOnly>("fecha_estimada")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("hora_llegada")
                        .HasColumnType("time(6)");

                    b.Property<int>("id_estado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("vehiculo_id")
                        .HasColumnType("int")
                        .HasColumnName("vehiculo_id");

                    b.HasKey("id_agendamiento");

                    b.HasIndex("id_estado");

                    b.HasIndex("vehiculo_id");

                    b.ToTable("agendamiento", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.ColaboradoresModel", b =>
                {
                    b.Property<int>("id_colaborador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_colaborador"));

                    b.Property<DateOnly>("fecha_contratacion")
                        .HasColumnType("date");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("puesto")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<decimal>("salario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("id_colaborador");

                    b.ToTable("colaboradores", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.DetalleFacturaModel", b =>
                {
                    b.Property<int>("id_detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_detalle"));

                    b.Property<decimal>("costo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("factura_id")
                        .HasColumnType("int")
                        .HasColumnName("factura_id");

                    b.Property<int>("servicio_id")
                        .HasColumnType("int")
                        .HasColumnName("servicio_id");

                    b.Property<decimal>("subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("id_detalle");

                    b.HasIndex("factura_id");

                    b.HasIndex("servicio_id");

                    b.ToTable("detalle_factura", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.EstadosModel", b =>
                {
                    b.Property<int>("id_estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_estado"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id_estado");

                    b.ToTable("estados", (string)null);

                    b.HasData(
                        new
                        {
                            id_estado = 1,
                            nombre = "activo"
                        },
                        new
                        {
                            id_estado = 2,
                            nombre = "pendiente"
                        },
                        new
                        {
                            id_estado = 3,
                            nombre = "inactivo"
                        },
                        new
                        {
                            id_estado = 4,
                            nombre = "Ingresado"
                        },
                        new
                        {
                            id_estado = 5,
                            nombre = "En Diagnóstico"
                        },
                        new
                        {
                            id_estado = 6,
                            nombre = "Pendiente de aprobación"
                        },
                        new
                        {
                            id_estado = 7,
                            nombre = "En mantenimiento"
                        },
                        new
                        {
                            id_estado = 8,
                            nombre = "En pruebas"
                        },
                        new
                        {
                            id_estado = 9,
                            nombre = "Finalizado"
                        },
                        new
                        {
                            id_estado = 10,
                            nombre = "Entregado"
                        },
                        new
                        {
                            id_estado = 11,
                            nombre = "Cancelado"
                        });
                });

            modelBuilder.Entity("Tecmave.Api.Models.FacturasModel", b =>
                {
                    b.Property<int>("id_factura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_factura"));

                    b.Property<int>("cliente_id")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("fecha_emision")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("metodo_pago")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("total")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("id_factura");

                    b.ToTable("factura", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.MarcasModel", b =>
                {
                    b.Property<int>("id_marca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_marca"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id_marca");

                    b.ToTable("marca", (string)null);

                    b.HasData(
                        new
                        {
                            id_marca = 1,
                            nombre = "Jeep"
                        },
                        new
                        {
                            id_marca = 2,
                            nombre = "Dodge"
                        },
                        new
                        {
                            id_marca = 3,
                            nombre = "Toyota"
                        },
                        new
                        {
                            id_marca = 4,
                            nombre = "Nissan"
                        },
                        new
                        {
                            id_marca = 5,
                            nombre = "Honda"
                        },
                        new
                        {
                            id_marca = 6,
                            nombre = "Mitsubishi"
                        },
                        new
                        {
                            id_marca = 7,
                            nombre = "Suzuki"
                        },
                        new
                        {
                            id_marca = 8,
                            nombre = "Hyundai"
                        },
                        new
                        {
                            id_marca = 9,
                            nombre = "Chevrolet"
                        },
                        new
                        {
                            id_marca = 10,
                            nombre = "Chrysler"
                        },
                        new
                        {
                            id_marca = 11,
                            nombre = "Daihatsu"
                        },
                        new
                        {
                            id_marca = 12,
                            nombre = "RAM"
                        },
                        new
                        {
                            id_marca = 13,
                            nombre = "Ford"
                        },
                        new
                        {
                            id_marca = 14,
                            nombre = "GMC"
                        },
                        new
                        {
                            id_marca = 15,
                            nombre = "Hummer"
                        },
                        new
                        {
                            id_marca = 16,
                            nombre = "Isuzu"
                        },
                        new
                        {
                            id_marca = 17,
                            nombre = "Kia"
                        },
                        new
                        {
                            id_marca = 18,
                            nombre = "Lexus"
                        },
                        new
                        {
                            id_marca = 19,
                            nombre = "Mazda"
                        });
                });

            modelBuilder.Entity("Tecmave.Api.Models.NotificacionesModel", b =>
                {
                    b.Property<int>("id_notificaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_notificaciones"));

                    b.Property<DateOnly>("fecha_envio")
                        .HasColumnType("date");

                    b.Property<int>("id_estado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<string>("mensaje")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("id_notificaciones");

                    b.HasIndex("id_estado");

                    b.ToTable("notificaciones", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.PromocionesModel", b =>
                {
                    b.Property<int>("id_promocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_promocion"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("fecha_fin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("fecha_inicio")
                        .HasColumnType("date");

                    b.Property<int>("id_estado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id_promocion");

                    b.HasIndex("id_estado");

                    b.ToTable("promociones", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.ResenasModel", b =>
                {
                    b.Property<int>("id_resena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_resena"));

                    b.Property<float>("calificacion")
                        .HasColumnType("float");

                    b.Property<string>("cliente_id")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cliente_id");

                    b.Property<string>("comentario")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("servicio_id")
                        .HasColumnType("int")
                        .HasColumnName("servicio_id");

                    b.HasKey("id_resena");

                    b.HasIndex("servicio_id");

                    b.ToTable("resenas", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.RevisionModel", b =>
                {
                    b.Property<int>("id_revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_revision"));

                    b.Property<DateTime>("fecha_entrega_final")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fecha_estimada_entrega")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fecha_ingreso")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_estado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("id_servicio")
                        .HasColumnType("int")
                        .HasColumnName("id_servicio");

                    b.Property<int>("vehiculo_id")
                        .HasColumnType("int")
                        .HasColumnName("vehiculo_id");

                    b.HasKey("id_revision");

                    b.HasIndex("id_estado");

                    b.HasIndex("id_servicio");

                    b.HasIndex("vehiculo_id");

                    b.ToTable("revision", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.RoleChangeAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ChangedByUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("NewRole")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PreviousRole")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("TargetUserId")
                        .HasColumnType("int");

                    b.Property<string>("TargetUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ChangedAtUtc");

                    b.HasIndex("TargetUserId");

                    b.ToTable("role_change_audit", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.ServiciosModel", b =>
                {
                    b.Property<int>("id_servicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_servicio"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("tipo_servicio_id")
                        .HasColumnType("int")
                        .HasColumnName("tipo_servicio_id");

                    b.HasKey("id_servicio");

                    b.HasIndex("tipo_servicio_id");

                    b.ToTable("servicios", (string)null);

                    b.HasData(
                        new
                        {
                            id_servicio = 1,
                            descripcion = "Diagnóstico y reparación de sistemas electrónicos",
                            nombre = "Electrónica",
                            precio = 120.00m,
                            tipo = "Falla específica",
                            tipo_servicio_id = 3
                        },
                        new
                        {
                            id_servicio = 2,
                            descripcion = "Revisión y reparación del sistema de A/C",
                            nombre = "Aire acondicionado",
                            precio = 150.00m,
                            tipo = "Falla específica",
                            tipo_servicio_id = 3
                        },
                        new
                        {
                            id_servicio = 3,
                            descripcion = "Reparación de cajas manual/automática",
                            nombre = "Transmisiones",
                            precio = 250.00m,
                            tipo = "Falla específica",
                            tipo_servicio_id = 3
                        },
                        new
                        {
                            id_servicio = 4,
                            descripcion = "Cableado, luces y alternadores",
                            nombre = "Electricidad",
                            precio = 100.00m,
                            tipo = "Falla específica",
                            tipo_servicio_id = 3
                        },
                        new
                        {
                            id_servicio = 5,
                            descripcion = "Reemplazo y sellado",
                            nombre = "Parabrisas",
                            precio = 180.00m,
                            tipo = "Falla específica",
                            tipo_servicio_id = 3
                        },
                        new
                        {
                            id_servicio = 6,
                            descripcion = "Reparación y limpieza de interiores",
                            nombre = "Tapicería",
                            precio = 130.00m,
                            tipo = "Falla específica",
                            tipo_servicio_id = 3
                        },
                        new
                        {
                            id_servicio = 7,
                            descripcion = "General o parcial",
                            nombre = "Pintura",
                            precio = 300.00m,
                            tipo = "Falla específica",
                            tipo_servicio_id = 3
                        },
                        new
                        {
                            id_servicio = 8,
                            descripcion = "Aceite y filtro",
                            nombre = "Cambio de aceite",
                            precio = 80.00m,
                            tipo = "Mantenimiento preventivo",
                            tipo_servicio_id = 1
                        },
                        new
                        {
                            id_servicio = 9,
                            descripcion = "Chequeo completo",
                            nombre = "Revisión general",
                            precio = 100.00m,
                            tipo = "Mantenimiento preventivo",
                            tipo_servicio_id = 1
                        },
                        new
                        {
                            id_servicio = 10,
                            descripcion = "Pastillas y discos",
                            nombre = "Cambio de frenos",
                            precio = 200.00m,
                            tipo = "Mantenimiento correctivo",
                            tipo_servicio_id = 2
                        },
                        new
                        {
                            id_servicio = 11,
                            descripcion = "Fallas graves",
                            nombre = "Reparación de motor",
                            precio = 500.00m,
                            tipo = "Mantenimiento correctivo",
                            tipo_servicio_id = 2
                        });
                });

            modelBuilder.Entity("Tecmave.Api.Models.ServiciosRevisionModel", b =>
                {
                    b.Property<int>("id_servicio_revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_servicio_revision"));

                    b.Property<decimal>("costo_final")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("revision_id")
                        .HasColumnType("int")
                        .HasColumnName("revision_id");

                    b.Property<int>("servicio_id")
                        .HasColumnType("int")
                        .HasColumnName("servicio_id");

                    b.HasKey("id_servicio_revision");

                    b.HasIndex("revision_id");

                    b.HasIndex("servicio_id");

                    b.ToTable("servicios_revision", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.TipoServiciosModel", b =>
                {
                    b.Property<int>("id_tipo_servicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_tipo_servicio"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id_tipo_servicio");

                    b.ToTable("tipo_servicios", (string)null);

                    b.HasData(
                        new
                        {
                            id_tipo_servicio = 1,
                            descripcion = "Servicios de mantenimiento periódico",
                            nombre = "Mantenimiento preventivo"
                        },
                        new
                        {
                            id_tipo_servicio = 2,
                            descripcion = "Reparaciones por fallas",
                            nombre = "Mantenimiento correctivo"
                        },
                        new
                        {
                            id_tipo_servicio = 3,
                            descripcion = "Diagnóstico/Reparación de una falla puntual",
                            nombre = "Falla específica"
                        });
                });

            modelBuilder.Entity("Tecmave.Api.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<int>("Anno")
                        .HasColumnType("int")
                        .HasColumnName("anno");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int")
                        .HasColumnName("id_marca");

                    b.Property<string>("Modelo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("placa");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("IdMarca");

                    b.ToTable("vehiculos", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.AgendamientoModel", b =>
                {
                    b.HasOne("Tecmave.Api.Models.EstadosModel", null)
                        .WithMany()
                        .HasForeignKey("id_estado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tecmave.Api.Models.Vehiculo", null)
                        .WithMany()
                        .HasForeignKey("vehiculo_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tecmave.Api.Models.DetalleFacturaModel", b =>
                {
                    b.HasOne("Tecmave.Api.Models.FacturasModel", null)
                        .WithMany()
                        .HasForeignKey("factura_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tecmave.Api.Models.ServiciosModel", null)
                        .WithMany()
                        .HasForeignKey("servicio_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tecmave.Api.Models.NotificacionesModel", b =>
                {
                    b.HasOne("Tecmave.Api.Models.EstadosModel", null)
                        .WithMany()
                        .HasForeignKey("id_estado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tecmave.Api.Models.PromocionesModel", b =>
                {
                    b.HasOne("Tecmave.Api.Models.EstadosModel", null)
                        .WithMany()
                        .HasForeignKey("id_estado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tecmave.Api.Models.ResenasModel", b =>
                {
                    b.HasOne("Tecmave.Api.Models.ServiciosModel", null)
                        .WithMany()
                        .HasForeignKey("servicio_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tecmave.Api.Models.RevisionModel", b =>
                {
                    b.HasOne("Tecmave.Api.Models.EstadosModel", null)
                        .WithMany()
                        .HasForeignKey("id_estado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tecmave.Api.Models.ServiciosModel", null)
                        .WithMany()
                        .HasForeignKey("id_servicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tecmave.Api.Models.Vehiculo", null)
                        .WithMany()
                        .HasForeignKey("vehiculo_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tecmave.Api.Models.ServiciosModel", b =>
                {
                    b.HasOne("Tecmave.Api.Models.TipoServiciosModel", null)
                        .WithMany()
                        .HasForeignKey("tipo_servicio_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tecmave.Api.Models.ServiciosRevisionModel", b =>
                {
                    b.HasOne("Tecmave.Api.Models.RevisionModel", null)
                        .WithMany()
                        .HasForeignKey("revision_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tecmave.Api.Models.ServiciosModel", null)
                        .WithMany()
                        .HasForeignKey("servicio_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tecmave.Api.Models.Vehiculo", b =>
                {
                    b.HasOne("Tecmave.Api.Models.MarcasModel", null)
                        .WithMany()
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
