// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tecmave.Api.Data;

#nullable disable

namespace Tecmave.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202050532_Cedula")]
    partial class Cedula
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetroleclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuserclaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("aspnetuserlogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("aspnetuserroles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("aspnetusertokens", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.AgendamientoModel", b =>
                {
                    b.Property<int>("id_agendamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_agendamiento"));

                    b.Property<int>("cliente_id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("fecha_agregada")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("fecha_estimada")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("hora_llegada")
                        .HasColumnType("time(6)");

                    b.Property<int>("id_estado")
                        .HasColumnType("int");

                    b.Property<int>("vehiculo_id")
                        .HasColumnType("int");

                    b.HasKey("id_agendamiento");

                    b.ToTable("agendamiento", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("aspnetroles", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.ColaboradoresModel", b =>
                {
                    b.Property<int>("id_colaborador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_colaborador"));

                    b.Property<DateOnly>("fecha_contratacion")
                        .HasColumnType("date");

                    b.Property<int>("id_usuario")
                        .HasColumnType("int");

                    b.Property<string>("puesto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("salario")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_colaborador");

                    b.ToTable("colaboradores", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.DetalleFacturaModel", b =>
                {
                    b.Property<int>("id_detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_detalle"));

                    b.Property<decimal>("costo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("factura_id")
                        .HasColumnType("int");

                    b.Property<int>("servicio_id")
                        .HasColumnType("int");

                    b.Property<decimal>("subtotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_detalle");

                    b.ToTable("detalle_factura", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.EstadosModel", b =>
                {
                    b.Property<int>("id_estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_estado"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_estado");

                    b.ToTable("estados", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.FacturasModel", b =>
                {
                    b.Property<int>("id_factura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_factura"));

                    b.Property<int?>("cliente_id")
                        .HasColumnType("int");

                    b.Property<string>("estado_pago")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("fecha_emision")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("metodo_pago")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("total")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id_factura");

                    b.ToTable("factura", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.MantenimientoModel", b =>
                {
                    b.Property<int>("IdMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdMantenimiento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMantenimiento"));

                    b.Property<DateOnly>("FechaMantenimiento")
                        .HasColumnType("date")
                        .HasColumnName("FechaMantenimiento");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("IdEstado");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int")
                        .HasColumnName("IdVehiculo");

                    b.Property<DateOnly?>("ProximoMantenimiento")
                        .HasColumnType("date")
                        .HasColumnName("ProximoMantenimiento");

                    b.Property<bool>("RecordatorioEnviado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("RecordatorioEnviado");

                    b.HasKey("IdMantenimiento");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("Mantenimientos", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.MarcasModel", b =>
                {
                    b.Property<int>("id_marca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_marca"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_marca");

                    b.ToTable("marca", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.NotificacionesModel", b =>
                {
                    b.Property<int>("id_notificaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_notificaciones"));

                    b.Property<DateOnly>("fecha_envio")
                        .HasColumnType("date");

                    b.Property<int>("id_estado")
                        .HasColumnType("int");

                    b.Property<int?>("id_promocion")
                        .HasColumnType("int");

                    b.Property<string>("mensaje")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("usuario_id")
                        .HasColumnType("int");

                    b.HasKey("id_notificaciones");

                    b.ToTable("notificaciones", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.PlanillasModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("colaborador_id")
                        .HasColumnType("int");

                    b.Property<decimal>("deducciones")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("fecha_generada")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("horas_trabajadas")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("neto_pagar")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("observaciones")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("periodo_fin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("periodo_inicio")
                        .HasColumnType("date");

                    b.Property<decimal>("total_salario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("valor_hora")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("id");

                    b.ToTable("planillas", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.PromocionEnvio", b =>
                {
                    b.Property<int>("IdEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_envio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEnvio"));

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_envio");

                    b.Property<int>("IdPromocion")
                        .HasColumnType("int")
                        .HasColumnName("id_promocion");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdEnvio");

                    b.ToTable("promocion_envios", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.PromocionesModel", b =>
                {
                    b.Property<int>("id_promocion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_promocion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_promocion"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly>("fecha_fin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("fecha_inicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("id_estado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<string>("imagen_url")
                        .HasColumnType("longtext")
                        .HasColumnName("imagen_url");

                    b.Property<bool>("recordatorio_enviado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("recordatorio_enviado");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("titulo");

                    b.HasKey("id_promocion");

                    b.ToTable("promociones", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.Recordatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaEnvio");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioId");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int")
                        .HasColumnName("VehiculoId");

                    b.HasKey("Id");

                    b.ToTable("recordatorios", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.ResenasModel", b =>
                {
                    b.Property<int>("id_resena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_resena"));

                    b.Property<float>("calificacion")
                        .HasColumnType("float");

                    b.Property<int>("cliente_id")
                        .HasColumnType("int");

                    b.Property<string>("comentario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("revision_id")
                        .HasColumnType("int");

                    b.HasKey("id_resena");

                    b.ToTable("resenas", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.RevisionModel", b =>
                {
                    b.Property<int>("id_revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_revision"));

                    b.Property<DateTime?>("fecha_entrega_final")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("fecha_estimada_entrega")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("fecha_ingreso")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("golpes_arriba")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("golpes_delantera")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("golpes_derecha")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("golpes_izquierda")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("golpes_trasera")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("id_agendamiento")
                        .HasColumnType("int");

                    b.Property<int>("id_estado")
                        .HasColumnType("int");

                    b.Property<int?>("kilometraje")
                        .HasColumnType("int");

                    b.Property<string>("nivel_combustible")
                        .HasColumnType("longtext");

                    b.Property<string>("notas_taller")
                        .HasColumnType("longtext");

                    b.Property<string>("observaciones_cliente")
                        .HasColumnType("longtext");

                    b.Property<int>("vehiculo_id")
                        .HasColumnType("int");

                    b.Property<bool>("vehiculo_mojado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("vehiculo_sucio")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id_revision");

                    b.ToTable("revision", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.RevisionPertenenciasModel", b =>
                {
                    b.Property<int>("id_pertenencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_pertenencia"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("presente")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("revision_id")
                        .HasColumnType("int");

                    b.HasKey("id_pertenencia");

                    b.ToTable("revision_pertenencias");
                });

            modelBuilder.Entity("Tecmave.Api.Models.RevisionTrabajosModel", b =>
                {
                    b.Property<int>("id_trabajo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_trabajo"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("realizado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("revision_id")
                        .HasColumnType("int");

                    b.HasKey("id_trabajo");

                    b.ToTable("revision_trabajos");
                });

            modelBuilder.Entity("Tecmave.Api.Models.RoleChangeAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ChangedByUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("NewRole")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PreviousRole")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("TargetUserId")
                        .HasColumnType("int");

                    b.Property<string>("TargetUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ChangedAtUtc");

                    b.HasIndex("TargetUserId");

                    b.ToTable("role_change_audit", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.ServiciosModel", b =>
                {
                    b.Property<int>("id_servicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_servicio"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("tipo_servicio_id")
                        .HasColumnType("int");

                    b.HasKey("id_servicio");

                    b.ToTable("servicios", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.ServiciosRevisionModel", b =>
                {
                    b.Property<int>("id_servicio_revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_servicio_revision"));

                    b.Property<decimal>("costo_final")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("revision_id")
                        .HasColumnType("int");

                    b.Property<int>("servicio_id")
                        .HasColumnType("int");

                    b.HasKey("id_servicio_revision");

                    b.ToTable("servicios_revision", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.TipoServiciosModel", b =>
                {
                    b.Property<int>("id_tipo_servicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id_tipo_servicio"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id_tipo_servicio");

                    b.ToTable("tipo_servicios", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cedula")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("NotificacionesActivadas")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("aspnetusers", (string)null);
                });

            modelBuilder.Entity("Tecmave.Api.Models.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_vehiculo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<int>("Anno")
                        .HasColumnType("int")
                        .HasColumnName("anno");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int")
                        .HasColumnName("id_marca");

                    b.Property<string>("Modelo")
                        .HasColumnType("longtext")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("placa");

                    b.Property<DateOnly?>("Proximo")
                        .HasColumnType("date");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("ClienteId");

                    b.ToTable("vehiculos", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Tecmave.Api.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Tecmave.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Tecmave.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Tecmave.Api.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tecmave.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Tecmave.Api.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tecmave.Api.Models.MantenimientoModel", b =>
                {
                    b.HasOne("Tecmave.Api.Models.EstadosModel", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Mantenimientos_Estado");

                    b.HasOne("Tecmave.Api.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Mantenimientos_vehiculos_IdVehiculo");

                    b.Navigation("Estado");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Tecmave.Api.Models.Vehiculo", b =>
                {
                    b.HasOne("Tecmave.Api.Models.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
